image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      gradle build -x test
    command: |
      gradle bootRun

ports:
  - port: 8123
    onOpen: open-browser

jetbrains:
  intellij:
    prebuilds:
      version: stable
